# Generated by Django 4.2.6 on 2023-10-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=400)),
                ('price', models.IntegerField()),
                ('currency', models.CharField(choices=[('USD', 'Dollar'), ('EUR', 'Euro'), ('RON', 'RON')], max_length=3)),
            ],
        ),
    ]
