# Generated by Django 4.2.6 on 2023-10-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_membership_color_alter_membership_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='currency',
            field=models.CharField(choices=[('$', 'Dollar'), ('€', 'Euro'), ('RON', 'Ron')], max_length=3),
        ),
    ]
