# Generated by Django 4.2.6 on 2023-10-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
