# Generated by Django 4.2.6 on 2023-10-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_provider_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='company_name',
            new_name='provider_name',
        ),
    ]
